version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/gitlab-runner/general-purpose"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/job-executor/general-purpose"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
