name: GitLab Runner

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

# Everything below should be common under all branches
jobs:
  image-build:
    uses: ./.github/workflows/reusable-image-build.yaml
    with:
      image_group: gitlab-runner
      image_type: general-purpose
      platforms: linux/amd64,linux/arm64
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
