name: GitLab Runner General Purpose

env:
  name: gitlab-runner

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/gitlab-runners-build.yaml"
      - "gitlab-runner/**"

defaults:
  run:
    working-directory: ./gitlab-runner

# Everything below should be common under all branches
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
        type:
          - general-purpose
      fail-fast: false
    services:
      local_docker_registry:
        image: registry:2
        ports:
          - 80:5000
    steps:
      - name: Checkout Code
        id: checkout_code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host
      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: "${{ env.name }}/${{ matrix.type }}"
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            "localhost/komailo/ci-images:${{ env.name }}-${{ matrix.type }}-${{ steps.get_parameters.outputs.tag }}"
