name: GitLab Runner General Purpose

env:
  name: gitlab-runner
  docker_registry: ghcr.io

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/gitlab-runners-build.yaml"
      - "gitlab-runner/**"

defaults:
  run:
    working-directory: ./gitlab-runner

# Everything below should be common under all branches
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
        type:
          - general-purpose
      fail-fast: false
    services:
      local_docker_registry:
        image: registry:2
        ports:
          - 80:5000
    steps:
      - name: Checkout Code
        id: checkout_code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.docker_registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: "${{ env.name }}/${{ matrix.type }}"
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            "${{ env.docker_registry }}/${{ github.repository }}:${{ env.name }}-${{ matrix.type }}-${{ github.ref }}"
